//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DXMVCTestApplication.Models.XPO
{

	[Indices(@"Patient;Date")]
	[Persistent(@"Appointment")]
	public partial class XPAppointment : XPObject
	{
		XPPatient fPatient;
		[Indexed(Name = @"iPatient_Appointment")]
		[Association(@"XPAppointmentReferencesXPPatient")]
		public XPPatient Patient
		{
			get { return fPatient; }
			set { SetPropertyValue<XPPatient>(nameof(Patient), ref fPatient, value); }
		}
		DateTime fDate;
		[Indexed(Name = @"iAppointment_Date")]
		public DateTime Date
		{
			get { return fDate; }
			set { SetPropertyValue<DateTime>(nameof(Date), ref fDate, value); }
		}
		double fDuration;
		public double Duration
		{
			get { return fDuration; }
			set { SetPropertyValue<double>(nameof(Duration), ref fDuration, value); }
		}
		bool fAllDayEvent;
		public bool AllDayEvent
		{
			get { return fAllDayEvent; }
			set { SetPropertyValue<bool>(nameof(AllDayEvent), ref fAllDayEvent, value); }
		}
		string fComment;
		public string Comment
		{
			get { return fComment; }
			set { SetPropertyValue<string>(nameof(Comment), ref fComment, value); }
		}
	}

}
