//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DXMVCTestApplication.Models.XPO
{

	[Persistent(@"Patient")]
	public partial class XPPatient : XPObject
	{
		string fFirstName;
		public string FirstName
		{
			get { return fFirstName; }
			set { SetPropertyValue<string>(nameof(FirstName), ref fFirstName, value); }
		}
		string fLastName;
		public string LastName
		{
			get { return fLastName; }
			set { SetPropertyValue<string>(nameof(LastName), ref fLastName, value); }
		}
		DateTime fBirthday;
		public DateTime Birthday
		{
			get { return fBirthday; }
			set { SetPropertyValue<DateTime>(nameof(Birthday), ref fBirthday, value); }
		}
		string fEmail;
		public string Email
		{
			get { return fEmail; }
			set { SetPropertyValue<string>(nameof(Email), ref fEmail, value); }
		}
		string fPhone;
		public string Phone
		{
			get { return fPhone; }
			set { SetPropertyValue<string>(nameof(Phone), ref fPhone, value); }
		}
		XPPicture fPicture;
		[Indexed(Name = @"iPicture_Patient")]
		public XPPicture Picture
		{
			get { return fPicture; }
			set { SetPropertyValue<XPPicture>(nameof(Picture), ref fPicture, value); }
		}
		string fAddress;
		public string Address
		{
			get { return fAddress; }
			set { SetPropertyValue<string>(nameof(Address), ref fAddress, value); }
		}
		[PersistentAlias("Concat(FirstName, ' ', LastName)")]
		public string FullName
		{
			get { return (string)(EvaluateAlias(nameof(FullName))); }
		}
		[Association(@"XPAppointmentReferencesXPPatient"), Aggregated]
		public XPCollection<XPAppointment> Appointments { get { return GetCollection<XPAppointment>(nameof(Appointments)); } }
	}

}
