//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DXMVCTestApplication.Models.XPO
{

	[Persistent(@"Picture")]
	public partial class XPPicture : XPObject
	{
		byte[] fImage;
		[Size(SizeAttribute.Unlimited)]
		[MemberDesignTimeVisibility(true)]
		public byte[] Image
		{
			get { return fImage; }
			set { SetPropertyValue<byte[]>(nameof(Image), ref fImage, value); }
		}
	}

}
